### PR TITLE
#5 - Feature - Add Test Fixture Summary table in File

### PR DESCRIPTION
**Pull request by arasu-rrk**
Added Test Fixture summary table in Files for NUnit Test Cases alone

### CODE REVIEW

**Comment by anshooarora** [comment]
Sorry, I still haven't merged this pull request.  I tested it against a few of my test files and the page becomes extremely lengthy because there are many fixtures.  I like your approach though and I prefer it over the masonry view we currently have.  This approach is much more cleaner but it makes sense to have either this or the masonry views.  I am not sure which to choose and will also discuss with the team about what they think.  I will update you soon.

**Comment by arasu-rrk** [comment]
Okay. If that is the case shall we have something like this

image

**Comment by anshooarora** [comment]
This looks really good.  I think we can provide this info when the user does a hover/onmouseover.

**Comment by anshooarora** [comment]
I think we can do it without the mouseover, it should be immediately apparent.  

Please send me a pull request and I will merge it.  Will try to release the next version sometime next week.  Cheers.

**Comment by arasu-rrk** [comment]
Okay. Sure. I will make the changes and update you

**Pull request closed without merging**
