### PR TITLE
Add Console Log output to individual test result display (Issue 14)

### PR DESCRIPTION
**Pull request by Wowbies**
I have a start to what I am looking for here. https://github.com/Wowbies/reportunit 
 - I Added the logs to the test "StatusMessage" for now): 
 - Note: it doesn't look good with the grid view. Log lines are wrapped a lot, and it is hard to navigate to the next test when the logs are really long (200 + lines)

### CODE REVIEW

**Comment by anshooarora** [comment]
Can you share a sample of your XML results file?  I will test with your pull request.  Would a modal dialog work fine to display this info?

**Comment by Wowbies** [comment]
A modal dialog would work great as long as it was big and could scroll.
It is going to take me some time to get you a good sample. (I am worried
that ours could have passwords etc into a secure system in it.) I will have
to create a sample project for testing purposes.

**Comment by anshooarora** [comment]
See this sample for example:  http://relevantcodes.com/Tools/ReportUnit/Gallio.html

In the right top-hand corner, when you click the info button, you will see a modal pop up.  How does it look?

**Comment by Wowbies** [comment]
Yes that is exactly what I was thinking. If you look at the latest version
it has an icon for the console logs, it scrolls etc. (I have an example in
my zip file)

**Comment by anshooarora** [comment]
I am merging your code but will require a results file to test and code out the part that creates modals for logs.

**Comment by anshooarora** [comment]
Btw, I have uploaded the latest samples as the one I shared with you was for v1.1.

Latest:  http://relevantcodes.com/Tools/ReportUnit/Gallio.html

**Comment by Wowbies** [comment]
It looks like my attachment was stripped from my email.  how do you want me to send you my examples

**Comment by anshooarora** [comment]
You can email me at anshooarora@gmail.com.

**Pull request merged**
